apiVersion: apps/v1
kind: Deployment
metadata:
  name: octa-app
  labels:
    app: octa-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: octa-app
  template:
    metadata:
      labels:
        app: octa-app
    spec:
      containers:
      - name: octa-app
        image: qaut/octa-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

